// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: logevnt.proto

package pb

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Guid        string               `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	Ip          string               `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Time        *timestamp.Timestamp `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	Method      string               `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	Path        string               `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	Status      int32                `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	ProcessTime int64                `protobuf:"varint,7,opt,name=process_time,json=processTime,proto3" json:"process_time,omitempty"`
	FullLog     string               `protobuf:"bytes,8,opt,name=full_log,json=fullLog,proto3" json:"full_log,omitempty"`
}

func (x *StartEventRequest) Reset() {
	*x = StartEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logevnt_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartEventRequest) ProtoMessage() {}

func (x *StartEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logevnt_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartEventRequest.ProtoReflect.Descriptor instead.
func (*StartEventRequest) Descriptor() ([]byte, []int) {
	return file_logevnt_proto_rawDescGZIP(), []int{0}
}

func (x *StartEventRequest) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *StartEventRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *StartEventRequest) GetTime() *timestamp.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *StartEventRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *StartEventRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *StartEventRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *StartEventRequest) GetProcessTime() int64 {
	if x != nil {
		return x.ProcessTime
	}
	return 0
}

func (x *StartEventRequest) GetFullLog() string {
	if x != nil {
		return x.FullLog
	}
	return ""
}

type StartEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Guid string `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
}

func (x *StartEventResponse) Reset() {
	*x = StartEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logevnt_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartEventResponse) ProtoMessage() {}

func (x *StartEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logevnt_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartEventResponse.ProtoReflect.Descriptor instead.
func (*StartEventResponse) Descriptor() ([]byte, []int) {
	return file_logevnt_proto_rawDescGZIP(), []int{1}
}

func (x *StartEventResponse) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

type EndEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Guid string `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
}

func (x *EndEventRequest) Reset() {
	*x = EndEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logevnt_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndEventRequest) ProtoMessage() {}

func (x *EndEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logevnt_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndEventRequest.ProtoReflect.Descriptor instead.
func (*EndEventRequest) Descriptor() ([]byte, []int) {
	return file_logevnt_proto_rawDescGZIP(), []int{2}
}

func (x *EndEventRequest) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

type EndEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Guid string `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
}

func (x *EndEventResponse) Reset() {
	*x = EndEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logevnt_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndEventResponse) ProtoMessage() {}

func (x *EndEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logevnt_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndEventResponse.ProtoReflect.Descriptor instead.
func (*EndEventResponse) Descriptor() ([]byte, []int) {
	return file_logevnt_proto_rawDescGZIP(), []int{3}
}

func (x *EndEventResponse) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

var File_logevnt_proto protoreflect.FileDescriptor

var file_logevnt_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6c, 0x6f, 0x67, 0x65, 0x76, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xe9, 0x01, 0x0a, 0x11, 0x53, 0x74, 0x61, 0x72, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x67, 0x75, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x67, 0x75, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x21,
	0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x6c, 0x6f, 0x67, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x75, 0x6c, 0x6c, 0x4c, 0x6f, 0x67, 0x22, 0x28, 0x0a, 0x12,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x67, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x67, 0x75, 0x69, 0x64, 0x22, 0x25, 0x0a, 0x0f, 0x45, 0x6e, 0x64, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x67, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x67, 0x75, 0x69, 0x64, 0x22, 0x26, 0x0a,
	0x10, 0x45, 0x6e, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x67, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x67, 0x75, 0x69, 0x64, 0x32, 0x6c, 0x0a, 0x08, 0x4c, 0x6f, 0x67, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x12, 0x32, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x12, 0x2e, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13,
	0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x2c, 0x0a, 0x03, 0x45, 0x6e, 0x64, 0x12, 0x10, 0x2e, 0x45,
	0x6e, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11,
	0x2e, 0x45, 0x6e, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x6c, 0x6f, 0x67, 0x65, 0x76, 0x6e, 0x74, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_logevnt_proto_rawDescOnce sync.Once
	file_logevnt_proto_rawDescData = file_logevnt_proto_rawDesc
)

func file_logevnt_proto_rawDescGZIP() []byte {
	file_logevnt_proto_rawDescOnce.Do(func() {
		file_logevnt_proto_rawDescData = protoimpl.X.CompressGZIP(file_logevnt_proto_rawDescData)
	})
	return file_logevnt_proto_rawDescData
}

var file_logevnt_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_logevnt_proto_goTypes = []interface{}{
	(*StartEventRequest)(nil),   // 0: StartEventRequest
	(*StartEventResponse)(nil),  // 1: StartEventResponse
	(*EndEventRequest)(nil),     // 2: EndEventRequest
	(*EndEventResponse)(nil),    // 3: EndEventResponse
	(*timestamp.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_logevnt_proto_depIdxs = []int32{
	4, // 0: StartEventRequest.time:type_name -> google.protobuf.Timestamp
	0, // 1: LogEvent.Start:input_type -> StartEventRequest
	2, // 2: LogEvent.End:input_type -> EndEventRequest
	1, // 3: LogEvent.Start:output_type -> StartEventResponse
	3, // 4: LogEvent.End:output_type -> EndEventResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_logevnt_proto_init() }
func file_logevnt_proto_init() {
	if File_logevnt_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_logevnt_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logevnt_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logevnt_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logevnt_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_logevnt_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_logevnt_proto_goTypes,
		DependencyIndexes: file_logevnt_proto_depIdxs,
		MessageInfos:      file_logevnt_proto_msgTypes,
	}.Build()
	File_logevnt_proto = out.File
	file_logevnt_proto_rawDesc = nil
	file_logevnt_proto_goTypes = nil
	file_logevnt_proto_depIdxs = nil
}
